import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "@/styles/globals.css";
import "@/public/pages/scss/pages.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lavender app",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
